# Generated by Django 4.0.3 on 2022-03-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("blog", "0005_blogpage_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="featured_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
