# Generated by Django 4.0.3 on 2022-03-29 01:39

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogpage_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='tag',
            field=modelcluster.fields.ParentalManyToManyField(related_name='+', to='blog.blogtag'),
        ),
    ]
