# Generated by Django 4.0.3 on 2022-04-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogpage_canonical_url_blogpage_og_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_actions',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_address_country',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_address_locality',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_address_postal',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_address_region',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_address_street',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_extra_json',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_geo_lat',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_geo_lng',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_hours',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_logo',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_name',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_phone',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='struct_org_type',
        ),
    ]
