# Generated by Django 4.0.3 on 2022-03-11 02:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "parallax_section",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
