# Generated by Django 4.0.3 on 2022-03-05 01:51

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
