# Generated by Django 4.0.3 on 2022-03-11 16:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_basicpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.core.fields.StreamField([('parallax_section', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(max_length=30, required=False)), ('sub_header', wagtail.core.blocks.CharBlock(max_length=250, required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('feature_list_section', wagtail.core.blocks.StructBlock([('feature', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('feature_name', wagtail.core.blocks.CharBlock(max_length=25, required=True)), ('feature_summary', wagtail.core.blocks.CharBlock(max_length=255, required=True))])))]))], blank=True, null=True),
        ),
    ]
