# Generated by Django 4.0.3 on 2022-03-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
