# Generated by Django 4.0.3 on 2022-03-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='showtime',
            name='matinee',
            field=models.BooleanField(default=False),
        ),
    ]
