# Generated by Django 4.0.3 on 2022-03-16 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_blogauthor_tagline"),
        ("website", "0031_movie_review_page_alter_showtime_show_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="review_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blog.blogpage",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="show_date",
            field=models.DateField(
                default=datetime.datetime(2022, 3, 16, 14, 58, 9, 529985, tzinfo=utc)
            ),
        ),
    ]
