# Generated by Django 4.0.3 on 2022-03-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0036_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="title",
            field=models.CharField(default="TITLE", max_length=50),
        ),
    ]
