# Generated by Django 4.0.3 on 2022-03-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0038_movie_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
    ]
