# Generated by Django 4.0.3 on 2022-03-19 01:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0039_alter_movie_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="IMDB ID"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="youtube_id",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="YouTube ID"
            ),
        ),
        migrations.CreateModel(
            name="ShowTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "show_date",
                    models.DateField(
                        default=datetime.datetime(
                            2022, 3, 19, 1, 41, 33, 64870, tzinfo=utc
                        )
                    ),
                ),
                ("show_time", models.TimeField()),
                ("matinee", models.BooleanField(default=False)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.movie",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
