# Generated by Django 4.0.3 on 2022-03-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0041_alter_showtime_page_alter_showtime_show_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShowTime",
        ),
    ]
