# Generated by Django 4.0.3 on 2022-03-19 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.AlterField(
            model_name='showtime',
            name='show_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 1, 52, 27, 562284, tzinfo=utc)),
        ),
    ]
