# Generated by Django 4.0.3 on 2022-03-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_alter_showtime_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='show_date',
            field=models.DateField(default=None),
        ),
    ]
