# Generated by Django 4.0.3 on 2022-05-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_remove_contactpage_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
