# Generated by Django 4.0.3 on 2022-05-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.theater'),
        ),
    ]
